// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qiyjzukzhwklkmpdxmfl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFpeWp6dWt6aHdrbGttcGR4bWZsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM3MTM2NzQsImV4cCI6MjA1OTI4OTY3NH0.I7ThYF_QyCiZOoJDrKazMW-Q2_TKVvKz8nfL7RBzZJE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});