// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ychheamigqjpxtnzqina.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InljaGhlYW1pZ3FqcHh0bnpxaW5hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxNTMyNDEsImV4cCI6MjA2OTcyOTI0MX0.qxMGdrrty_oTFIoa-ZIGtOA1t8VGhMLIf7iZ6MPbilE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});